name: Python Build
description: 'Build release distributions for Python package'

inputs:
  python-version:
    description: 'Python version to use'
    required: false
    default: '3.12'
  version-name:
    description: 'Version name of the package'
    required: true

runs:
  using: "composite"
  permissions:
    packages: write
  steps:
  - name: Set up Python ${{ inputs.python-version }}
    uses: actions/setup-python@v5
    with:
      python-version: ${{ inputs.python-version }}
      cache: pip
      cache-dependency-path: |
        requirements.txt

  - name: Build release distributions
    run: |
      python -m pip install --upgrade pip build
      python -m build

  - name: Upload artifact
    uses: actions/upload-artifact@v4
    with:
      name: ${{ inputs.version-name }}
      path: dist/
