name: Python Linter
description: 'Run pre-commit hooks to lint Python code'

inputs:
  python-version:
    description: 'Python version to use'
    required: false
    default: '3.12'

runs:
  using: "composite"
  steps:
  - uses: actions/setup-python@v5
    with:
      python-version: ${{ inputs.python-version }}
      cache: pip
      cache-dependency-path: |
        requirements.txt
        .pre-commit-config.yaml

  - uses: pre-commit/action@v3.0.0

  - name: Lint Summary
    if: always()
    shell: bash
    run: |
      echo "### 🔍 Linting Results" >> $GITHUB_STEP_SUMMARY
      if [ ${{ job.status }} == 'success' ]; then
        echo "✅ All linting checks passed" >> $GITHUB_STEP_SUMMARY
      else
        echo "❌ Linting failed" >> $GITHUB_STEP_SUMMARY
      fi
